dns:
  server:
    addr: "ns1.rusty-leipzig.com:53"
    zone: "rusty-leipzig.com."
    tsigKey: "tsig-key."
    tsigSecret: "tsig-secret"
  client:
    syncInterval: 1800
    healthCheckInterval: 60
    guards:
      immutable:
        - A/dnsify # IPV4 Records for `dnsify.[zone]`
        - A/dns # IPV4 Records for `dns.[zone]`
        - "*/ns1" # All record types for `ns1.[zone]`
        - "*/ns2"
        - "*/ns3"
        - NS/@ # NS Records for the zone
      admin_only:
        - A/@
        - AAAA/@
        - A/www
        - AAAA/www

httpServer:
  host: "localhost"
  port: 8080
  secureCookie: false

oauth2Client:
  clientID: "dns"
  clientSecret: "yourClientSecret"
  redirectURL: "http://localhost:8080/oauth/callback"
  AuthURL: "http://localhost:9999/auth"
  TokenURL: "http://localhost:9999/token"
