dnsClient:
  tsigKey: "tsig-key."
  tsigSecret: "tsig-secret"
  host: "157.230.106.145"
  port: 53
  zone: "rusty-leipzig.com."
  syncInterval: 30
  guards:
    immutable:
      - dnsify
      - dns
      - ns1
      - ns2
      - ns3
    admin_only:
      - www

httpServer:
  host: "localhost"
  port: 8080
  secureCookie: false

oauth2Client:
  clientID: "dns"
  clientSecret: "yourClientSecret"
  redirectURL: "http://localhost:8080/oauth/callback"
  AuthURL: "http://localhost:9999/auth"
  TokenURL: "http://localhost:9999/token"
